# NumPy基础
## NumPy的ndarray: 一种多维数据对象
NumPy最重要的一个特点就是N维数组对象(即ndarray)，该对象是一个快速而灵活的大数据集容器。你可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素的运算一样：

In [18]:
import numpy as np
data = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr1 = np.array(data)
arr1 * 10 

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
data +  data

[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [5, 6, 7, 8]]

ndarray是一个通用的同构数据多维容器，也就是说，其中的所有元素必须是相同类型的。每个数据都有一个shape(表示各维度大小的元组）和一个dtype(一个用于说明数据元组类型的对象)： 

In [20]:
arr1.shape

(2, 4)

In [21]:
arr1.dtype

dtype('int32')

### 创建ndarray
创建数组的最简单方式就是使用array函数。它接收一切序列型的对象，然后产生一个新的含有传入数据的Numpy数组。以一个列表的转换为例：

In [22]:
import numpy as np
data = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr1 = np.array(data)

除了特殊说明，np.array会尝试为新建的这个数据推断一个较为合适的数据类型。除np.arrray之外，还有一些函数可以新建数组。比如zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需闯入一个表示形状的元组即可：

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

arange是Python内置函数range的数组版：

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray 的数据类型
dtpye是一个特殊的对象，它含有ndarry将一块内存解释为特定数据类型所需的信息：

In [27]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

可以通过ndarray的astype方法显式地转换器dtype：

In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [32]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

如果将浮点数转换成整数，则小数部分会被截断。如果某字符串表示的全是数字，也可以用astype将其转换为数值形式：

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])